esphome:
  name: sensor_botijao_gas
  platform: ESP8266
  board: d1_mini

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:

api:

sensor:
  - platform: hx711
    name: "Peso do Botijão"
    dout_pin: D0
    clk_pin: D1
    gain: 128
    update_interval: 1s
    accuracy_decimals: 2
    filters:
      - filter_out: nan
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1    
      - calibrate_linear:
          - -218400 -> 0
          - -253000 -> 4.9
    unit_of_measurement: kg